name: Conoce los principales Triggers (Conditionals)

# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  obtener_paso_actual:
    name: Verificar paso actual
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: obtener_paso
        run: |
          echo "paso_actual=2" >> $GITHUB_OUTPUT
    outputs:
      paso_actual: ${{ steps.obtener_paso.outputs.paso_actual }}

  conoce_triggers:
    name: Conoce los principales Triggers
    needs: obtener_paso_actual

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 2
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.obtener_paso_actual.outputs.paso_actual == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        uses: echo "Hello!!"

  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: node main.js